spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/whyaneel/azsc-config-server.git
          username: whyaneel
          password: e8a92d753d0a55d54cd49233e3197e6f2eb491b8
