security:
  oauth2:
    client:
      clientId: teambuildingapp
      client-secret: XUoJBrTtqXBonU5zMVzSUtrLPKRQztLUQE4poDoIR1QdcDfGgnGgJO5wbFC7xCEL
      accessTokenUri: http://gateway/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  zipkin:
    sender:
      type: web
  main:
    allow-bean-definition-overriding: true

server:
  servlet:
    context-path: /

feign:
  hystrix:
    enabled: true
